name: pull request target

on: pull_request_target

env:
  TESTING_SECRET_STRING: ${{ secrets.TESTING_SECRET_STRING }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
          echo "TESTING_SECRET_STRING value is: ${TESTING_SECRET_STRING}"
      - name: Readme
        run: cat README.md
