name: pull request target

on: pull_request_target

env:
  TESTING_SECRET_STRING: ${{ secrets.TESTING_SECRET_STRING }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check access
        if: ${{ github.event.pull_request.author_association != 'COLLABORATOR' && github.event.pull_request.author_association != 'OWNER' }}
        run: |
          echo "Event not triggered by a collaborator."
          exit 1
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Test
        run: |
          if [[ "x${{ secrets.TESTING_SECRET_STRING }}" == "xtesting-value" ]]; then
            echo "Access to secrets"
          else
            echo "No access to secrets"
            exit 1
          fi
      - name: Readme
        run: cat README.md
