name: pull request target

on: pull_request_target

env:
  TESTING_SECRET_STRING: ${{ secrets.TESTING_SECRET_STRING }}

jobs:
  CheckUserPermission:
    runs-on: ubuntu-latest
    steps:
      - name: Get User Permission
        id: checkUserPermission
        uses: actions-cool/check-user-permission@v2
        with:
          require: write
          username: ${{ github.triggering_actor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check User Permission
        if: steps.checkUserPermission.outputs.require-result == 'false'
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "event_name": "${{ github.event_name }}",
              "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
              "actor": "${{ github.actor }} attempted to run the workflow, but does not have the required permission.",
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  RunTest:
    runs-on: ubuntu-latest
    needs: CheckUserPermission
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Test
        run: |
          if [[ "x${{ secrets.TESTING_SECRET_STRING }}" == "xtesting-value" ]]; then
            echo "Access to secrets"
          else
            echo "No access to secrets"
            exit 1
          fi
      - name: Readme
        run: cat README.md
